services:
  notifications-worker:
    container_name: notifications-worker
    build:
        context: .
    env_file:
      - .env
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
    networks:
        - archium-network
    labels:
      - "traefik.enable=true"

networks:
  archium-network:
    external: true